### ISSUE TITLE
Uncaught Swoole\Error: Socket#41 has already been bound to another coroutine#7, reading of the same socket in coroutine#5

### ISSUE THREAD

**Issue by volodymyr-hordiienko** [hyperf-ext/mail#13]
Sometimes get this error message, could you help with understanding what can cause this issue? Thanks

PHP Fatal error:  Uncaught Swoole\Error: Socket#41 has already been bound to another coroutine#7, reading of the same socket in coroutine#5 at the same time is not allowed in /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:162
Stack trace:
#0 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(162): fgets()
#1 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(469): Swift_Transport_StreamBuffer->readLine()
#2 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(342): Swift_Transport_AbstractSmtpTransport->getFullResponse()
#3 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#4 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(392): Swift_Transport_EsmtpTransport->executeCommand()
#5 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(499): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#6 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#7 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#8 /opt/www/vendor/hyperf-ext/mail/src/Transport/SmtpTransport.php(99): Swift_Transport_AbstractSmtpTransport->send()
#9 /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): HyperfExt\Mail\Transport\SmtpTransport->send()
#10 /opt/www/vendor/hyperf-ext/mail/src/Mailer.php(269): Swift_Mailer->send()
#11 /opt/www/vendor/hyperf-ext/mail/src/Mailer.php(183): HyperfExt\Mail\Mailer->sendSwiftMessage()
#12 /opt/www/vendor/hyperf-ext/mail/src/Mailable.php(385): HyperfExt\Mail\Mailer->sendNow()
#13 /opt/www/vendor/hyperf-ext/mail/src/QueuedMailableJob.php(32): HyperfExt\Mail\Mailable->send()
#14 /opt/www/vendor/hyperf/async-queue/src/Driver/Driver.php(130): HyperfExt\Mail\QueuedMailableJob->handle()
#15 /opt/www/vendor/hyperf/utils/src/Coroutine/Concurrent.php(80): Hyperf\AsyncQueue\Driver\Driver->Hyperf\AsyncQueue\Driver\{closure}()
#16 /opt/www/vendor/hyperf/utils/src/Functions.php(274): Hyperf\Utils\Coroutine\Concurrent->Hyperf\Utils\Coroutine\{closure}()
#17 /opt/www/vendor/hyperf/utils/src/Coroutine.php(62): call()
#18 {main}
  thrown in /opt/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 162

**Comment by jenawant** [comment]
确实遇到了这个问题，PHP8+Hyperf3.0，请求支援

**Comment by jenawant** [comment]
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

**Comment by buexplain** [comment]
这个邮件发送包没有池化底层的socket对象，所以不能被多个协程同时使用。
解决方法是：每次发送邮件都构造一个新的`HyperfExt\Mail\Contracts\MailerInterface`对象。
具体是代码：
 https://github.com/hyperf-ext/mail/blob/2c1a54ceae87d9fa1c386eafc5d615e9bfbb5d1d/src/MailManager.php#L78
改为如下即可：
```php
public function get(string $name): MailerInterface
{
     return $this->resolve($name);
}
```
