### ISSUE TITLE
[ERROR] Entry "HyperfExt\Mail\Transport\AwsSesTransport" cannot be resolved: Entry "Aws\Ses\SesClient" cannot be resolved: 

### ISSUE THREAD

**Issue by develop-lilun** [hyperf-ext/mail#7]
`[ERROR] Entry "HyperfExt\Mail\Transport\AwsSesTransport" cannot be resolved: Entry "Aws\Ses\SesClient" cannot be resolved: Parameter $args of __construct() has no value defined or guessable
Full definition:
Object[Aws\Ses\SesClient]
Full definition:
Object[HyperfExt\Mail\Transport\AwsSesTransport][20] in /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Exception/InvalidDefinitionException.php
[ERROR] #0 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Resolver/ObjectResolver.php(103): Hyperf\Di\Exception\InvalidDefinitionException::create(Object(Hyperf\Di\Definition\ObjectDefinition), 'Entry "HyperfEx...')
#1 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Resolver/ObjectResolver.php(66): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#2 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(62): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#3 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Resolver/DepthGuard.php(73): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#4 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(63): Hyperf\Di\Resolver\DepthGuard->call('HyperfExt\\Mail\\...', Object(Closure))
#5 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Container.php(194): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#6 /Users/ll/www/user-thinkcar/vendor/hyperf/di/src/Container.php(82): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#7 /Users/ll/www/user-thinkcar/vendor/hyperf/utils/src/Functions.php(420): Hyperf\Di\Container->make('HyperfExt\\Mail\\...', Array)
#8 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(124): make('HyperfExt\\Mail\\...', Array)
#9 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(179): HyperfExt\Mail\MailManager->createTransport(Array)
#10 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(153): HyperfExt\Mail\MailManager->createSwiftMailer(Array)
#11 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(90): HyperfExt\Mail\MailManager->resolve('aws_ses')
#12 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(81): HyperfExt\Mail\MailManager->get('aws_ses')
#13 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/Mailable.php(454): HyperfExt\Mail\MailManager->mailer('aws_ses')
#14 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/Mailable.php(383): HyperfExt\Mail\Mailable->resolveMailer(Object(HyperfExt\Mail\MailManager))
#15 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/MailManager.php(106): HyperfExt\Mail\Mailable->send(Object(HyperfExt\Mail\MailManager))
#16 /Users/ll/www/user-thinkcar/vendor/hyperf-ext/mail/src/PendingMail.php(151): HyperfExt\Mail\MailManager->send(Object(App\Mail\OrderShipped))
#17 /Users/ll/www/user-thinkcar/runtime/container/proxy/App_Serivces_SendServices.proxy.php(65): HyperfExt\Mail\PendingMail->send(Object(App\Mail\OrderShipped))
#18 /Users/ll/www/user-thinkcar/runtime/container/proxy/App_Controller_V1_SendController.proxy.php(50): App\Serivces\SendServices->setEmailLoginCode('2', '348845608@qq.co...', NULL)
#19 /Users/ll/www/user-thinkcar/vendor/hyperf/http-server/src/CoreMiddleware.php(161): App\Controller\V1\SendController->sendEmailVerifiableCode()
#20 /Users/ll/www/user-thinkcar/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\HttpServer\CoreMiddleware->handleFound(Object(Hyperf\HttpServer\Router\Dispatched), Object(Hyperf\HttpMessage\Server\Request))
#21 /Users/ll/www/user-thinkcar/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\HttpServer\CoreMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#22 /Users/ll/www/user-thinkcar/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#23 /Users/ll/www/user-thinkcar/vendor/hyperf/validation/src/Middleware/ValidationMiddleware.php(83): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#24 /Users/ll/www/user-thinkcar/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Validation\Middleware\ValidationMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#25 /Users/ll/www/user-thinkcar/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#26 /Users/ll/www/user-thinkcar/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#27 /Users/ll/www/user-thinkcar/vendor/hyperf/http-server/src/Server.php(117): Hyperf\Dispatcher\HttpDispatcher->dispatch(Object(Hyperf\HttpMessage\Server\Request), Array, Object(Hyperf\HttpServer\CoreMiddleware))
#28 {main}
`

aws_ses 发送报错。

**Comment by cesarli** [comment]
解决了吗，我也遇到了这个问题

**Comment by develop-lilun** [comment]
> 解决了吗，我也遇到了这个问题

未解决

**Comment by develop-lilun** [comment]
这个包感觉好垃圾呀
